accounts:

  hjxh_normal:
    sid: xiaohu2
    appkey: xiaohu2-jd
    appsecret: c2e1b5354142067cf0f360a36ceb8e7a

  adxes_normal:
    sid: adexe2
    appkey: adexe2-jd
    appsecret: 308e19f4ffc962c814c3462659b1e693
